# AutoShutdown Configuration File
# This file contains all the settings for the AutoShutdown mod

[General Settings]
# The command name to trigger auto shutdown detection
commandName = "autoshutdown"

# Time to wait in minutes before shutting down when no players are online
# Range: 1-60 minutes
waitTimeMinutes = 5

# Whether to shutdown the computer after closing the server
# WARNING: This will attempt to shutdown the entire computer!
shutdownComputer = false

# Message prefix for all auto shutdown messages
messagePrefix = "[AutoShutdown] "